platform :ios,’7.0’
pod 'ZXingObjC','~>3.1.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'MPColorTools', '~> 1.6.1'
pod 'Masonry', '~> 0.6.2'

pod 'AFNetworking', '~> 2.6.0'
pod 'AFNetworkingHelper', '~> 0.1.4'

pod 'HexColors', '~> 2.3.0'
pod 'MJRefresh'
pod 'MJExtension', '~> 3.0.8'
pod 'YYKit', '~> 0.9.10'


